/* Workbench — Angle Lab
   Strings only. Add a language by adding a block here. */
export default {
  en:{
    modAng:"Angle Lab",
    modAngP:"Tell acute from right from obtuse — and catch a reflex.",
    gAngL:"Protractor",
    gAngLP:"Swing the arm, watch the name change.",
    gAngN:"Name it",
    gAngNP:"What kind of angle is this?",
    gAngM:"Make it",
    gAngMP:"Drag until it matches.",
    angle:"Angle",
    kinds:"Kinds of angle",
    dragAng:"DRAG TO SWING THE ARM",
    snap5:"Snap 5°",
    ticksT:"Ticks",
    jump:"Jump to",
    qAngN:"What kind of angle is this?",
    qAngM:"Make this kind of angle:",
    check:"Check it",
    nextA:"Next angle",
    tacute:"Acute",
    tright:"Right",
    tobtuse:"Obtuse",
    tstraight:"Straight",
    treflex:"Reflex",
    tzero:"No angle",
    racute:"UNDER 90°",
    rright:"EXACTLY 90°",
    robtuse:"90° TO 180°",
    rstraight:"EXACTLY 180°",
    rreflex:"OVER 180°",
    rzero:"0°",
    why:{
          acute:function(d){return d+"° is under 90°, so it's acute.";},
          right:function(d){return "Exactly 90° — that's a right angle.";},
          obtuse:function(d){return d+"° sits between 90° and 180°, so it's obtuse.";},
          straight:function(d){return "Exactly 180° — the two arms make a straight line.";},
          reflex:function(d){return d+"° is more than 180°, so it's reflex.";},
          zero:function(d){return "The arms are on top of each other.";}
        },
    youMade:function(d,n){return "You made "+d+"° — that's "+n.toLowerCase()+".";},
    arcHowA:"A line sweeps around the protractor. Tap the instant the angle matches the number shown.",
    ruleAim:"Bang on — 1000 points, minus 100 for every degree off",
    ruleBlueA:"Blue target — the same points, plus 1 extra second on the clock",
    ruleMiss:"Tapping outside the shaded band — 500 points off"
  },
  vi:{
    modAng:"Xưởng Góc",
    modAngP:"Phân biệt góc nhọn, góc vuông, góc tù — và bắt được góc phản.",
    gAngL:"Thước đo góc",
    gAngLP:"Xoay cạnh góc, xem tên góc đổi theo.",
    gAngN:"Gọi tên góc",
    gAngNP:"Đây là góc gì?",
    gAngM:"Tạo góc",
    gAngMP:"Kéo cho đúng loại góc.",
    angle:"Góc",
    kinds:"Các loại góc",
    dragAng:"KÉO ĐỂ XOAY CẠNH GÓC",
    snap5:"Bước 5°",
    ticksT:"Vạch chia",
    jump:"Nhảy tới",
    qAngN:"Đây là góc gì?",
    qAngM:"Hãy tạo một góc loại này:",
    check:"Kiểm tra",
    nextA:"Góc khác",
    tacute:"Góc nhọn",
    tright:"Góc vuông",
    tobtuse:"Góc tù",
    tstraight:"Góc bẹt",
    treflex:"Góc phản",
    tzero:"Chưa có góc",
    racute:"NHỎ HƠN 90°",
    rright:"ĐÚNG 90°",
    robtuse:"TỪ 90° ĐẾN 180°",
    rstraight:"ĐÚNG 180°",
    rreflex:"LỚN HƠN 180°",
    rzero:"0°",
    why:{
          acute:function(d){return d+"° nhỏ hơn 90°, nên là góc nhọn.";},
          right:function(d){return "Đúng 90° — đây là góc vuông.";},
          obtuse:function(d){return d+"° nằm giữa 90° và 180°, nên là góc tù.";},
          straight:function(d){return "Đúng 180° — hai cạnh nằm trên một đường thẳng.";},
          reflex:function(d){return d+"° lớn hơn 180°, nên là góc phản.";},
          zero:function(d){return "Hai cạnh đang chồng lên nhau.";}
        },
    youMade:function(d,n){return "Bạn tạo góc "+d+"° — đây là "+n.toLowerCase()+".";},
    arcHowA:"Một cạnh quét quanh thước đo góc. Chạm đúng lúc góc bằng số đã cho.",
    ruleAim:"Thật chuẩn — 1000 điểm, lệch mỗi độ trừ 100 điểm",
    ruleBlueA:"Mục tiêu xanh — điểm y như vậy, cộng thêm 1 giây",
    ruleMiss:"Chạm ngoài vùng tô đậm — trừ 500 điểm"
  }
};
