/* Workbench — Data Lab
   Strings only. Add a language by adding a block here. */
export default {
  en:{
    gDlSort:"Sort It",
    gDlSortP:"Drag items into the diagram that matches both of their properties.",
    gDlChart:"Chart Bench",
    gDlChartP:"Same data, four different pictures — tally, pictogram, bar chart, dot plot.",
    gDlQuiz:"Read the Data",
    gDlQuizP:"Read a chart, then answer a question about it.",

    dlSortHelp:"Drag an item to where it belongs — or tap it, then tap the spot. Tap a placed item to bring it back.",
    dlModeVenn:"Venn Diagram",
    dlModeCarroll:"Carroll Diagram",
    dlNewRound:"New Round",
    dlPropShape:function(name){return "Is a "+name+"?";},
    dlPropColor:function(name){return "Is "+name+"?";},
    dlPropWheels:"Has 2 Wheels?",
    dlPropEngine:"Has an Engine?",
    numOdd:"Is Odd?",
    numMult3:"Multiple of 3?",
    numMult5:"Multiple of 5?",
    numGt10:"Greater than 10?",
    dlYes:"Yes",
    dlNo:"No",
    dlOutside:"Neither",
    dlAllSorted:"Everything found its group!",

    dlChartHelp:"Tap a button to see the same data drawn a different way.",
    dlNewData:"New Data",
    dlViewTally:"Tally Chart",
    dlViewPicto:"Pictogram",
    dlViewBar:"Bar Chart",
    dlViewDot:"Dot Plot",
    dlKeyLbl:"Key:",
    dlKeyEquals:"= 1",

    dlQMost:"Which shape appears the most?",
    dlQLeast:"Which shape appears the least?",
    dlQHowMany:function(name){return "How many "+name+"s are there?";},
    dlQDiff:function(a,b){return "How many more "+a+"s than "+b+"s are there?";},
    dlQTotal:"What is the total number of shapes?",
    dlQCompare:function(name){return "Which group has more "+name+"s?";},
    dlGroupA:"Group A",
    dlGroupB:"Group B",

    dlWhyMost:function(name,n){return "The tallest bar is "+name+", with "+n+".";},
    dlWhyLeast:function(name,n){return "The shortest bar is "+name+", with "+n+".";},
    dlWhyHowMany:function(name,n){return "Counting every "+name+" gives "+n+".";},
    dlWhyDiff:function(a,na,b,nb,d){return na+" "+a+"s minus "+nb+" "+b+"s is "+d+".";},
    dlWhyTotal:function(parts,n){return parts+" = "+n+".";},
    dlWhyCompare:function(which,name,n1,n2){return which+" has more "+name+"s ("+n1+" vs "+n2+").";},
    nextQ:"Next question"
  },
  vi:{
    gDlSort:"Phân Loại",
    gDlSortP:"Kéo các mục vào sơ đồ đúng với cả hai đặc điểm của nó.",
    gDlChart:"Bàn Biểu Đồ",
    gDlChartP:"Cùng một dữ liệu, bốn cách vẽ khác nhau — bảng kiểm đếm, tượng hình, biểu đồ cột, biểu đồ chấm.",
    gDlQuiz:"Đọc Dữ Liệu",
    gDlQuizP:"Đọc một biểu đồ, rồi trả lời câu hỏi về nó.",

    dlSortHelp:"Kéo một mục đến nơi nó thuộc về — hoặc chạm vào nó rồi chạm vào chỗ đó. Chạm vào mục đã đặt để đưa nó trở lại.",
    dlModeVenn:"Sơ Đồ Venn",
    dlModeCarroll:"Sơ Đồ Carroll",
    dlNewRound:"Vòng Mới",
    dlPropShape:function(name){return "Là "+name+"?";},
    dlPropColor:function(name){return "Màu "+name+"?";},
    dlPropWheels:"Có 2 Bánh Xe?",
    dlPropEngine:"Có Động Cơ?",
    numOdd:"Là Số Lẻ?",
    numMult3:"Là Bội Số Của 3?",
    numMult5:"Là Bội Số Của 5?",
    numGt10:"Lớn Hơn 10?",
    dlYes:"Có",
    dlNo:"Không",
    dlOutside:"Không phải cả hai",
    dlAllSorted:"Mọi thứ đã tìm được nhóm của mình!",

    dlChartHelp:"Chạm một nút để xem cùng dữ liệu được vẽ theo cách khác.",
    dlNewData:"Dữ Liệu Mới",
    dlViewTally:"Bảng Kiểm Đếm",
    dlViewPicto:"Biểu Đồ Tượng Hình",
    dlViewBar:"Biểu Đồ Cột",
    dlViewDot:"Biểu Đồ Chấm",
    dlKeyLbl:"Chú thích:",
    dlKeyEquals:"= 1",

    dlQMost:"Hình nào xuất hiện nhiều nhất?",
    dlQLeast:"Hình nào xuất hiện ít nhất?",
    dlQHowMany:function(name){return "Có bao nhiêu hình "+name+"?";},
    dlQDiff:function(a,b){return "Hình "+a+" nhiều hơn hình "+b+" bao nhiêu?";},
    dlQTotal:"Tổng số hình là bao nhiêu?",
    dlQCompare:function(name){return "Nhóm nào có nhiều hình "+name+" hơn?";},
    dlGroupA:"Nhóm A",
    dlGroupB:"Nhóm B",

    dlWhyMost:function(name,n){return "Cột cao nhất là "+name+", với "+n+".";},
    dlWhyLeast:function(name,n){return "Cột thấp nhất là "+name+", với "+n+".";},
    dlWhyHowMany:function(name,n){return "Đếm từng hình "+name+" được "+n+".";},
    dlWhyDiff:function(a,na,b,nb,d){return na+" hình "+a+" trừ "+nb+" hình "+b+" là "+d+".";},
    dlWhyTotal:function(parts,n){return parts+" = "+n+".";},
    dlWhyCompare:function(which,name,n1,n2){return which+" có nhiều hình "+name+" hơn ("+n1+" so với "+n2+").";},
    nextQ:"Câu tiếp theo"
  }
};
