/* Workbench — Fraction Lab
   Strings only. Add a language by adding a block here. */
export default {
  en:{
    gBench:"Fraction Bench",
    gBenchP:"Cut a strip and shade the parts.",
    gCmp:"Compare it",
    gCmpP:"Is it bigger, smaller or the same?",
    gOf:"Fraction of",
    gOfP:"One third of twelve is how many?",
    gAdd:"Add & take away",
    gAddP:"Same denominator, no tricks.",
    parts:"Parts",
    equiv:"Same value as",
    benchHelp:"More parts means smaller parts. Drag the sliders and watch.",
    numerator:"Numerator",
    denominator:"Denominator",
    fewer:"Fewer",
    more:"More",
    numNone:"None",
    numAll:"All",
    qCmp:"Which symbol goes in the middle?",
    ofWord:"of",
    nextQ:"Next question",
    gRun:"Arcade",
    gRunP:"Steer into the right lane. Don't slow down.",
    arcHowR:"You run faster with every gate. Steer into the lane whose answer is right.",
    ruleRunGood:"Right lane \u2014 500 points and 1 extra second",
    ruleRunBad:"Wrong lane \u2014 200 points off",
    ruleRunFast:"Every gate makes you 5% faster",
    ruleRunBoost:"Hold \u25B2 (or the up arrow key) to go faster",
    qAdd:"What is the answer?",
    ofWhy:function(n,d,w,a){return "Split "+w+" into "+d+" equal groups of "+(w/d)+". "+
          (n===1?"One group is ":n+" groups are ")+a+".";},
    cmpWhy:function(a,b,sym){return a+" "+sym+" "+b+".";},
    addWhy:function(a,op,b,r){return a+" "+op+" "+b+" = "+r+" \u2014 the denominator never changes.";},
    smallerWhy:"The more parts a whole is cut into, the smaller each part is."
  },
  vi:{
    gBench:"Bàn Phân Số",
    gBenchP:"Cắt một băng giấy rồi tô các phần.",
    gCmp:"So sánh",
    gCmpP:"Lớn hơn, nhỏ hơn hay bằng nhau?",
    gOf:"Phân số của",
    gOfP:"Một phần ba của mười hai là mấy?",
    gAdd:"Cộng & trừ",
    gAddP:"Cùng mẫu số, không rắc rối.",
    parts:"Số phần",
    equiv:"Bằng với",
    benchHelp:"Càng chia nhiều phần thì mỗi phần càng nhỏ. Kéo các thanh trượt mà xem.",
    numerator:"Tử số",
    denominator:"Mẫu số",
    fewer:"Ít hơn",
    more:"Nhiều hơn",
    numNone:"Không có",
    numAll:"Tất cả",
    qCmp:"Dấu nào điền vào giữa?",
    ofWord:"của",
    nextQ:"Câu tiếp theo",
    gRun:"Đua điểm",
    gRunP:"Lái vào đúng làn. Đừng chậm lại.",
    arcHowR:"Mỗi cổng đi qua bạn chạy nhanh hơn. Hãy lái vào làn có đáp án đúng.",
    ruleRunGood:"Đúng làn \u2014 500 điểm và thêm 1 giây",
    ruleRunBad:"Sai làn \u2014 trừ 200 điểm",
    ruleRunFast:"Mỗi cổng đi qua tăng tốc 5%",
    ruleRunBoost:"Giữ \u25B2 (hoặc phím mũi tên lên) để chạy nhanh hơn",
    qAdd:"Kết quả là bao nhiêu?",
    ofWhy:function(n,d,w,a){return "Chia "+w+" thành "+d+" nhóm bằng nhau, mỗi nhóm "+(w/d)+". "+
          (n===1?"Một nhóm là ":n+" nhóm là ")+a+".";},
    cmpWhy:function(a,b,sym){return a+" "+sym+" "+b+".";},
    addWhy:function(a,op,b,r){return a+" "+op+" "+b+" = "+r+" \u2014 mẫu số không đổi.";},
    smallerWhy:"Chia một cái thành càng nhiều phần thì mỗi phần càng nhỏ."
  }
};
