/* Workbench — Solid Lab
   Strings only. Add a language by adding a block here. */
export default {
  en:{
    modCube:"Solid Lab",
    modCubeP:"Flatten a solid into paper — then fold it back up.",
    gFold:"Fold Lab",
    gNet:"Folds or not?",
    gOpp:"Opposite sides",
    gFoldP:"Unfold five different solids.",
    gNetP:"Does this paper make a cube?",
    gOppP:"Which square lands across?",
    shape:"Shape",
    fold:"Fold",
    flat:"FLAT",
    solid:"SOLID",
    foldIt:"Fold it up",
    flatten:"Flatten it",
    drag:"DRAG THE MAT TO LOOK AROUND",
    reset:"Reset view",
    nets:"Nets",
    netsHelp:function(n,name){return "All "+n+" ways to unfold a "+name+". Nothing else folds up.";},
    sCube:"cube",
    sTetra:"triangle pyramid",
    sPyr:"square pyramid",
    sPrism:"triangle prism",
    sOcta:"octahedron",
    qNet:"Would this fold into a cube?",
    yes:"It folds",
    no:"It doesn't",
    qOpp:"Tap the square that ends up opposite the ★.",
    next:"Next shape",
    nextO:"Next puzzle",
    okNet:"Yes — it folds.",
    badNet:"No — it doesn't.",
    okNetW:"All six squares land on six different sides.",
    clashW:function(n,h){return n+" squares land on the same side"+(h?", so the box has "+h+" hole"+(h>1?"s":""):"")+".";},
    oppOk:function(a,b){return "Square "+a+" and square "+b+" never touch — they end up on opposite sides.";},
    oppBad:function(a,b,c){return "Square "+a+" touches the ★ square when it folds. The one across is square "+c+".";},
    arcHow:"Tap the shapes that fold into a cube. The faster you tap one, the more it's worth.",
    ruleGold:"Gold shape — up to 200 points, if you are quick",
    ruleBlue:"Blue shape — the same points, plus 1 extra second on the clock",
    ruleWrong:"Wrong shape — 100 points off"
  },
  vi:{
    modCube:"Xưởng Hình Khối",
    modCubeP:"Trải một khối thành giấy phẳng, rồi gấp lại.",
    gFold:"Gấp thử",
    gNet:"Gấp được không?",
    gOpp:"Mặt đối diện",
    gFoldP:"Trải năm khối khác nhau.",
    gNetP:"Tờ giấy này có thành khối lập phương không?",
    gOppP:"Ô nào nằm đối diện?",
    shape:"Khối",
    fold:"Gấp",
    flat:"PHẲNG",
    solid:"KHỐI",
    foldIt:"Gấp lại",
    flatten:"Trải phẳng",
    drag:"KÉO NỀN ĐỂ XOAY",
    reset:"Xoay về giữa",
    nets:"Hình trải",
    netsHelp:function(n,name){return "Cả "+n+" cách trải một "+name+". Ngoài ra thì không gấp được.";},
    sCube:"khối lập phương",
    sTetra:"khối chóp tam giác",
    sPyr:"khối chóp vuông",
    sPrism:"khối lăng trụ tam giác",
    sOcta:"khối bát diện",
    qNet:"Hình này có gấp thành khối lập phương không?",
    yes:"Gấp được",
    no:"Không được",
    qOpp:"Chạm vào ô sẽ nằm đối diện ô ★.",
    next:"Hình khác",
    nextO:"Câu khác",
    okNet:"Đúng — gấp được.",
    badNet:"Không — gấp không được.",
    okNetW:"Sáu ô rơi vào đúng sáu mặt khác nhau.",
    clashW:function(n,h){return n+" ô rơi vào cùng một mặt"+(h?", nên khối bị hở "+h+" chỗ":"")+".";},
    oppOk:function(a,b){return "Ô "+a+" và ô "+b+" không bao giờ chạm nhau — hai ô nằm đối diện.";},
    oppBad:function(a,b,c){return "Ô "+a+" chạm vào ô ★ khi gấp. Ô đối diện là ô "+c+".";},
    arcHow:"Chạm vào những hình gấp được thành khối lập phương. Chạm càng nhanh thì điểm càng cao.",
    ruleGold:"Hình vàng — tối đa 200 điểm nếu nhanh tay",
    ruleBlue:"Hình xanh — điểm y như hình vàng, cộng thêm 1 giây",
    ruleWrong:"Hình sai — trừ 100 điểm"
  }
};
