/* Workbench — Symmetry Lab
   Strings only. Add a language by adding a block here. */
export default {
  en:{
    gSymL:"Line Lab",
    gSymLP:"Pick a shape. Watch its lines of symmetry light up.",
    gSymQ:"Symmetrical or not?",
    gSymQP:"Is the dashed line a line of symmetry?",
    shapesHdr:"Shapes",
    symHdr:"Symmetry",
    linesOfSym:"Lines of symmetry",
    qLine:"Is the dashed line a line of symmetry?",
    yesSym:"It matches",
    noSym:"It doesn't",
    nextS:"Next shape",
    matchWhy:"Everything has a twin across the line — it's a true line of symmetry.",
    gapWhy:function(n){return "The line misses "+n+(n===1?" square":" squares")+" — not a line of symmetry.";},
    gapWhyPoly:"This shape's own lines of symmetry don't lie along the dashed line — not a line of symmetry.",
    sRing:"Square",
    sCross:"Cross",
    sRect:"Rectangle",
    sTriUp:"Triangle",
    sTriSide:"Sideways triangle",
    sStair1:"Staircase",
    sStair2:"Mirror staircase",
    sSquare:"Square",
    sDiamond:"Diamond",
    sTriangle:"Triangle",
    sPentagon:"Pentagon",
    sHexagon:"Hexagon",
    sHeptagon:"Heptagon",
    sOctagon:"Octagon",
    arcHowSym:"A line spins around the shape. Tap the instant it lines up with one of the shape's own lines of symmetry.",
    arcHowRevolver:"The shape spins in place and the marker stays still. Tap the instant one of the shape's own lines of symmetry lines up with it.",
    modePick:"Choose a mode",
    modeSweeper:"Sweeper",
    modeRevolver:"Revolver",
    ruleSymPerfect:"Within 1° — 500 points, dead on",
    ruleSymGood:"1° to 5° off — still counts, fewer points the further off",
    ruleSymMiss:"More than 5° from every line of symmetry — 300 points off",
    ruleSymBlue:"Blue shape — the same points, plus 1 extra second on the clock",
    symPerfect:"PERFECT",
    symGood:"GOOD",
    gMirror:"Mirror It",
    gMirrorP:"Tap points to mirror the shape into all four quadrants.",
    mgHow:"Tap points to mirror the shape into the other 3 quadrants.",
    mgAllDone:"All three mirrors match — perfectly symmetric!"
  },
  vi:{
    gSymL:"Vẽ Hình",
    gSymLP:"Chọn một hình. Xem đường đối xứng của nó sáng lên.",
    gSymQ:"Đối Xứng Hay Không?",
    gSymQP:"Đường kẻ đứt có phải là đường đối xứng không?",
    shapesHdr:"Hình",
    symHdr:"Đối xứng",
    linesOfSym:"Đường đối xứng",
    qLine:"Đường kẻ đứt có phải là đường đối xứng không?",
    yesSym:"Khớp nhau",
    noSym:"Không khớp",
    nextS:"Hình khác",
    matchWhy:"Mọi thứ đều có phần đối xứng qua đường kẻ — đây đúng là đường đối xứng.",
    gapWhy:function(n){return "Đường kẻ này thiếu "+n+" ô — không phải là đường đối xứng.";},
    gapWhyPoly:"Các đường đối xứng thật của hình này không trùng với đường kẻ đứt — đây không phải là đường đối xứng.",
    sRing:"Hình vuông",
    sCross:"Hình chữ thập",
    sRect:"Hình chữ nhật",
    sTriUp:"Hình tam giác",
    sTriSide:"Tam giác nằm nghiêng",
    sStair1:"Bậc thang",
    sStair2:"Bậc thang ngược",
    sSquare:"Hình vuông",
    sDiamond:"Hình thoi",
    sTriangle:"Tam giác",
    sPentagon:"Ngũ giác",
    sHexagon:"Lục giác",
    sHeptagon:"Thất giác",
    sOctagon:"Bát giác",
    arcHowSym:"Một đường thẳng xoay quanh hình. Chạm đúng lúc nó trùng với một đường đối xứng của hình.",
    arcHowRevolver:"Hình tự xoay tại chỗ, còn vạch đánh dấu đứng yên. Chạm đúng lúc một đường đối xứng của hình trùng với vạch đó.",
    modePick:"Chọn chế độ",
    modeSweeper:"Đường Quét",
    modeRevolver:"Hình Xoay",
    ruleSymPerfect:"Lệch dưới 1° — 500 điểm, chuẩn xác",
    ruleSymGood:"Lệch từ 1° đến 5° — vẫn tính điểm, lệch càng nhiều điểm càng ít",
    ruleSymMiss:"Lệch hơn 5° so với mọi đường đối xứng — trừ 300 điểm",
    ruleSymBlue:"Hình màu xanh dương — điểm y như vậy, cộng thêm 1 giây",
    symPerfect:"CHUẨN",
    symGood:"TỐT",
    gMirror:"Đối Xứng Gương",
    gMirrorP:"Chạm các điểm để soi hình vào cả bốn góc.",
    mgHow:"Chạm các điểm để soi hình vào 3 góc còn lại.",
    mgAllDone:"Cả ba hình soi gương đều đúng — đối xứng hoàn hảo!"
  }
};
