/* Workbench — Telling Time
   Strings only. Add a language by adding a block here. */
export default {
  en:{
    gClock:"Clock Bench",
    gClockP:"Drag the hands and watch the digital time keep up.",
    gCal:"Calendar & Units",
    gCalP:"How many days in a month? How many minutes in an hour?",
    gRead:"Read the Clock",
    gReadP:"What time does the clock show?",
    gConvert:"12-Hour or 24-Hour?",
    gConvertP:"Match the same time written the other way.",
    gElapsed:"Elapsed Time",
    gElapsedP:"Work out how long it's been, or what time it'll be.",
    hour:"Hour",
    minute:"Minute",
    ampm:"Morning or afternoon",
    am:"am",
    pm:"pm",
    leapYear:"Leap year",
    leapOn:"Leap year (29 days)",
    leapOff:"Not a leap year (28 days)",
    leapHelp:"Every 4 years, February gets an extra day.",
    clkWeeks:"Weeks",
    clkHours:"Hours",
    weeksEq:function(w,d){return w+(w===1?" week":" weeks")+" = "+d+" days";},
    hoursEq:function(h,m,s){return h+(h===1?" hour":" hours")+" = "+m+" minutes = "+s+" seconds";},
    daysCount:function(mon,n){return mon+" has "+n+" days.";},
    mon0:"January", mon1:"February", mon2:"March", mon3:"April",
    mon4:"May", mon5:"June", mon6:"July", mon7:"August",
    mon8:"September", mon9:"October", mon10:"November", mon11:"December",
    qRead:"What time does the clock show?",
    readWhy:function(truth){return "The hour hand and minute hand together show "+truth+".";},
    qTo24:"Write this as a 24-hour time.",
    qTo12:"Write this as a 12-hour time.",
    convertWhy:function(t12,t24){return t12+" and "+t24+" are the same moment — just written two ways.";},
    qDuration:"How long is it from the first time to the second?",
    qEndTime:function(dur){return "It's "+dur+" later. What time is it now?";},
    elapsedWhy:function(s,e,dur){return "From "+s+" to "+e+" is "+dur+".";},
    clkMins:"minutes",
    clkMin1:"minute",
    clkHrs:"hours",
    clkHr1:"hour",
    nextQ:"Next question"
  },
  vi:{
    gClock:"Đồng Hồ",
    gClockP:"Kéo kim đồng hồ và xem giờ điện tử thay đổi theo.",
    gCal:"Lịch & Đơn Vị Thời Gian",
    gCalP:"Một tháng có bao nhiêu ngày? Một giờ có bao nhiêu phút?",
    gRead:"Xem Đồng Hồ",
    gReadP:"Đồng hồ đang chỉ mấy giờ?",
    gConvert:"Giờ 12 Hay Giờ 24?",
    gConvertP:"Nối cùng một thời điểm viết theo hai cách.",
    gElapsed:"Khoảng Thời Gian",
    gElapsedP:"Tính xem đã trôi qua bao lâu, hoặc bây giờ là mấy giờ.",
    hour:"Giờ",
    minute:"Phút",
    ampm:"Sáng hay chiều",
    am:"sáng",
    pm:"chiều",
    leapYear:"Năm nhuận",
    leapOn:"Năm nhuận (29 ngày)",
    leapOff:"Không phải năm nhuận (28 ngày)",
    leapHelp:"Cứ 4 năm một lần, tháng Hai có thêm một ngày.",
    clkWeeks:"Tuần",
    clkHours:"Giờ",
    weeksEq:function(w,d){return w+" tuần = "+d+" ngày";},
    hoursEq:function(h,m,s){return h+" giờ = "+m+" phút = "+s+" giây";},
    daysCount:function(mon,n){return mon+" có "+n+" ngày.";},
    mon0:"Tháng Một", mon1:"Tháng Hai", mon2:"Tháng Ba", mon3:"Tháng Tư",
    mon4:"Tháng Năm", mon5:"Tháng Sáu", mon6:"Tháng Bảy", mon7:"Tháng Tám",
    mon8:"Tháng Chín", mon9:"Tháng Mười", mon10:"Tháng Mười Một", mon11:"Tháng Mười Hai",
    qRead:"Đồng hồ đang chỉ mấy giờ?",
    readWhy:function(truth){return "Kim giờ và kim phút cùng chỉ "+truth+".";},
    qTo24:"Viết lại thời gian này theo giờ 24.",
    qTo12:"Viết lại thời gian này theo giờ 12.",
    convertWhy:function(t12,t24){return t12+" và "+t24+" là cùng một thời điểm — chỉ viết khác nhau thôi.";},
    qDuration:"Từ thời điểm đầu đến thời điểm sau là bao lâu?",
    qEndTime:function(dur){return "Đã trôi qua "+dur+". Bây giờ là mấy giờ?";},
    elapsedWhy:function(s,e,dur){return "Từ "+s+" đến "+e+" là "+dur+".";},
    clkMins:"phút",
    clkMin1:"phút",
    clkHrs:"giờ",
    clkHr1:"giờ",
    nextQ:"Câu tiếp theo"
  }
};
